services:
  web:
    container_name: flask_app
    build: .
    volumes:
      - .:/flask-app
      - /flask-app/.venv
    command: gunicorn -w 4 app:app -b 0.0.0.0:5000

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - web