services:
  web:
    container_name: flask_app
    build: .
    ports:
      - "127.0.0.1:5555:5000"
    volumes:
      - .:/flask-app
      - /flask-app/.venv
    command: gunicorn -w 4 app:app -b 0.0.0.0:5000
